"""Stage 1 — hand keypoint regression (the only stage of hands_recognition).

A single non-conversational stage: it trains the whole HandPoseNet on synthetic
keypoint data. No text sources (the ModelSpec's loader generates frames), no mood, and
it IS the frozen base (there are no behavioral LoRA sectors here). Gate metric: mpjpe.
"""

from __future__ import annotations

from src.plugins import StageGate, StagePlugin

PLUGIN = StagePlugin(
    number=1,
    slug="keypoints",
    name="Hand keypoint regression",
    entry_level=1,
    frozen_base=True,
    rehearsal_fraction=0.0,  # single stage → nothing earlier to rehearse
    gate=StageGate(metric_key="mpjpe", threshold=0.05, label="Hand pose — mean keypoint error"),
    # No mood, no freeze point (single-stage model: nothing to freeze a core against).
    sources={},  # data is generated by the ModelSpec loader, not prepared to disk
)
